USER_SOURCES = source.c
EXECUTABLE = BSP.exe
###################################
SOURCE_DIR = src
OBJECT_DIR = build
BINARY_DIR = bin
EXTERN_DIR = ext
###################################
CC = cl
LINK = link
CFLAGS = /Ox /c /Fo.\$(OBJECT_DIR)\ \
/I $(EXTERN_DIR)\MulticoreBSP-for-C\ \
/I $(EXTERN_DIR)\unistd\include \
/I $(EXTERN_DIR)\pthreads-win32\sources\pthreads-w32-2-9-1-release \
/D HAVE_STRUCT_TIMESPEC

LIBS = $(EXTERN_DIR)\pthreads-win32\sources\pthreads-w32-2-9-1-release\pthreadVC2.lib

DLLS = $(BINARY_DIR)\pthreadVC2.dll
DLLS_SRC = $(EXTERN_DIR)\pthreads-win32\sources\pthreads-w32-2-9-1-release\pthreadVC2.dll

SOURCES = $(SOURCE_DIR)\$(USER_SOURCES)
OBJECTS = $(OBJECT_DIR)\$(USER_SOURCES:.c=.obj) $(EXTERN_DIR)\multicorebsp-for-c\*.obj

BINARY = $(BINARY_DIR)\$(EXECUTABLE)

all: $(BINARY) $(DLLS) $(OBJECTS)

echo_objects:
	echo $(OBJECTS)

echo_sources:
	echo $(SOURCES)

$(BINARY): $(OBJECTS)
	$(LINK) $(OBJECTS) $(LIBS) /OUT:$(BINARY)

$(DLLS): $(DLLS_SRC)
	copy $** $@

{$(SOURCE_DIR)\}.c{$(OBJECT_DIR)\}.obj::
	$(CC) $(CFLAGS) $<

clean:
	del $(OBJECT_DIR)\*.obj $(BINARY_DIR)\*.dll $(BINARY_DIR)\*.exe